# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'macOS Deployment'
        required: true
        default: 'macOS Deployment'


jobs:
  macOSJDK8:

    runs-on: macos-latest

    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          name: my-artifact
          path: /Users/runner/work/Brotli4j/
      - name: Build with Maven
        run: mvn -B -ntp clean package --file pom.xml
