# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'macOS Deployment'
        required: true
        default: 'macOS Deployment'


jobs:
  macOSBuild:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -B -ntp clean package --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOSBuild
          path: /Users/runner/work/Brotli4j/


  LinuxBuild:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -B -ntp clean package --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LinuxBuild
          path: /home/runner/work/Brotli4j/

  WindowsBuild:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.5.0
      - name: Build with Maven
        run: mvn -B -ntp clean package --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: WindowsBuild
          path: D:\a\Brotli4j\
