# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'


jobs:
  buildOnJDK8:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -B -ntp clean compile --file pom.xml
